package main

import "time"

type SpotlightType int

const (
	SpotWelcome SpotlightType = iota
	SpotRepo
	SpotTopic
	SpotGame
	SpotHelp
	SpotShoutout
)

func (t SpotlightType) String() string {
	switch t {
	case SpotWelcome:
		return "welcome"
	case SpotRepo:
		return "repo"
	case SpotTopic:
		return "topic"
	case SpotGame:
		return "game"
	case SpotHelp:
		return "help"
	case SpotShoutout:
		return "shoutout"
	}
	return "spotlight"
}

type Comment struct {
	Author   string
	Body     string
	At       time.Time
	Likes    int
	Liked    bool
	Comments []Comment
}

type Commit struct {
	SHA      string
	Author   string
	Message  string
	At       time.Time
	Likes    int
	Liked    bool
	Comments []Comment
}

type Branch struct {
	Name    string
	Commits []Commit
}

func seedBranches() []Branch {
	now := time.Now()
	h := func(d time.Duration) time.Time { return now.Add(-d) }

	return []Branch{
		{
			Name: "main",
			Commits: []Commit{
				{
					SHA: "a1b2c3d", Author: "@yamlhater", At: h(12 * time.Minute),
					Message: `another day, another auto-generated README that gaslights me about features that don't exist. the grift is full stack now.`,
					Likes:   2417,
					Comments: []Comment{
						{
							Author: "@nullpointer", Body: "I asked it to write tests and it wrote assertions for the bugs.",
							At: h(8 * time.Minute), Likes: 612,
							Comments: []Comment{
								{Author: "@yamlhater", Body: "you fool, the bugs ARE the spec now", At: h(7 * time.Minute), Likes: 198},
								{Author: "@senior_intern", Body: "deleted the tests, ship it", At: h(6 * time.Minute), Likes: 84},
							},
						},
						{
							Author: "@junior_dev", Body: "wait that's not a feature?",
							At: h(5 * time.Minute), Likes: 47,
							Comments: []Comment{
								{Author: "@recovering_pm", Body: "we'll roadmap it", At: h(4 * time.Minute), Likes: 23},
							},
						},
						{Author: "@devops_bard", Body: "the README is the product. always was.", At: h(3 * time.Minute), Likes: 311},
					},
				},
				{
					SHA: "9f8e7d6", Author: "@recovering_pm", At: h(47 * time.Minute),
					Message: `the AI summary of the meeting was wrong about literally everything except the fact that the meeting happened.`,
					Likes:   1893,
					Liked:   true,
				},
				{
					SHA: "3a3a3a3", Author: "@nullpointer", At: h(2 * time.Hour),
					Message: `spent three hours debugging code an LLM swore was correct. the inline comments were also lies. the commit message was a haiku.`,
					Likes:   864,
					Comments: []Comment{
						{Author: "@yamlhater", Body: "post the haiku, coward", At: h(time.Hour)},
					},
				},
				{
					SHA: "11ee22f", Author: "@standup_ghost", At: h(5 * time.Hour),
					Message: `landing page generated by AI. copy generated by AI. screenshot of the product also generated by AI. the product does not exist.`,
					Likes:   3402,
				},
			},
		},
		{
			Name: "feature/ai-takes",
			Commits: []Commit{
				{
					SHA: "deadbef", Author: "@ai_grifter", At: h(20 * time.Minute),
					Message: `your model is not "reasoning". it's pattern matching against Stack Overflow circa 2019. please stop putting it in airplanes.`,
					Likes:   5921,
					Liked:   true,
					Comments: []Comment{
						{Author: "@senior_intern", Body: "and circa 2019 stackoverflow was already wrong about half the time", At: h(15 * time.Minute)},
					},
				},
				{
					SHA: "cab1e57", Author: "@devops_bard", At: h(time.Hour),
					Message: `the context window is now bigger than my actual context. I have forgotten what I was working on. the model has not.`,
					Likes:   2110,
				},
				{
					SHA: "7c0ffee", Author: "@nullpointer", At: h(3 * time.Hour),
					Message: `every "AI startup" this quarter is a chat interface bolted onto a SQL query bolted onto a Notion doc someone exported in 2022.`,
					Likes:   4488,
				},
				{
					SHA: "babe123", Author: "@yamlhater", At: h(7 * time.Hour),
					Message: `we replaced our QA team with an LLM. the LLM also replaced our bug tracker, our roadmap, and the part of management that used to lie to investors.`,
					Likes:   3271,
					Comments: []Comment{
						{Author: "@recovering_pm", Body: "honestly an upgrade", At: h(6 * time.Hour)},
					},
				},
			},
		},
		{
			Name: "feature/corporate-life",
			Commits: []Commit{
				{
					SHA: "0ff1ce5", Author: "@corporate_villain", At: h(33 * time.Minute),
					Message: `synergy meeting tomorrow to align on the synergy meeting we had last week about synergy. attendance optional but tracked.`,
					Likes:   8104,
					Liked:   true,
				},
				{
					SHA: "okrokr0", Author: "@recovering_pm", At: h(2 * time.Hour),
					Message: `Q3 OKR review: we hit 31% of our goals, which is technically green if you set the bar at "the building did not catch fire".`,
					Likes:   2876,
					Comments: []Comment{
						{Author: "@standup_ghost", Body: "the building caught fire in Q1, you're cooking the books", At: h(time.Hour)},
						{Author: "@corporate_villain", Body: "we re-scoped the fire", At: h(45 * time.Minute)},
					},
				},
				{
					SHA: "manager1", Author: "@junior_dev", At: h(4 * time.Hour),
					Message: `my manager scheduled a 1:1 to ask if I'm okay because I was 4 minutes late to a meeting that started 6 minutes late.`,
					Likes:   6312,
				},
				{
					SHA: "deck404", Author: "@devops_bard", At: h(20 * time.Hour),
					Message: `the slide deck is 84 pages. the meeting is 25 minutes. there are no questions allowed. there will be a quiz.`,
					Likes:   1947,
				},
			},
		},
		{
			Name: "feature/job-market",
			Commits: []Commit{
				{
					SHA: "hir3me", Author: "@tech_recruiter_helper", At: h(50 * time.Minute),
					Message: `hiring senior engineer. 12 years of Rust required (language is 9 years old). salary: $85k. equity: morally.`,
					Likes:   9213,
					Liked:   true,
					Comments: []Comment{
						{Author: "@yamlhater", Body: "do you also need 15 years of Bun experience", At: h(45 * time.Minute)},
						{Author: "@nullpointer", Body: "the equity bit is killing me", At: h(40 * time.Minute)},
					},
				},
				{
					SHA: "fam1ly7", Author: "@corporate_villain", At: h(2 * time.Hour),
					Message: `we're a fast-paced family-style team that values radical candor, unpaid overtime, and crying in the bathroom (encouraged, not required).`,
					Likes:   4533,
				},
				{
					SHA: "remote0", Author: "@standup_ghost", At: h(6 * time.Hour),
					Message: `remote-friendly* (*you must be in our SF office for hybrid Tuesday, Wednesday, Thursday, alternate Mondays, and team-bonding Fridays).`,
					Likes:   3877,
				},
				{
					SHA: "round12", Author: "@junior_dev", At: h(28 * time.Hour),
					Message: `passed rounds 1-7 of the interview. round 8 is a take-home where I rewrite their entire backend in a weekend "for fit". what is fit. what am I.`,
					Likes:   5621,
					Comments: []Comment{
						{Author: "@ai_grifter", Body: "you ARE fit. you ARE the backend.", At: h(20 * time.Hour)},
					},
				},
			},
		},
		{
			Name: "release/shipping",
			Commits: []Commit{
				{
					SHA: "ship1tt", Author: "@nullpointer", At: h(15 * time.Minute),
					Message: `shipped the bug fix, which turned out to be a feature, which is now also a bug. the changelog reads like a confession.`,
					Likes:   1241,
				},
				{
					SHA: "selfapp", Author: "@yamlhater", At: h(time.Hour),
					Message: `PR approved by myself. pushed to main. nature is healing.`,
					Likes:   2098,
					Liked:   true,
				},
				{
					SHA: "r0llbck", Author: "@devops_bard", At: h(3 * time.Hour),
					Message: `rolled back the rollback of the rollback. git log reads like a Christopher Nolan movie. everything is fine.`,
					Likes:   1764,
					Comments: []Comment{
						{Author: "@standup_ghost", Body: "which timeline are we in", At: h(2 * time.Hour)},
					},
				},
				{
					SHA: "fr1day7", Author: "@junior_dev", At: h(53 * time.Hour),
					Message: `Friday afternoon deploy. 5pm. unsupervised. what's the worst that could happen. (it's now Monday and I am writing this from a bunker.)`,
					Likes:   3982,
				},
			},
		},
		{
			Name: "feature/devlife",
			Commits: []Commit{
				{
					SHA: "stack0v", Author: "@senior_intern", At: h(40 * time.Minute),
					Message: `tech stack: react, next, tailwind, shadcn, prisma, postgres, redis, kafka, k8s, terraform, datadog. product: a todo list.`,
					Likes:   7102,
				},
				{
					SHA: "vibesck", Author: "@standup_ghost", At: h(2 * time.Hour),
					Message: `code review feedback: "this is fine but vibes are off". I rewrote the whole module. vibes are now on. tests still failing.`,
					Likes:   2890,
					Liked:   true,
				},
				{
					SHA: "n0sleep", Author: "@yamlhater", At: h(7 * time.Hour),
					Message: `it works on my machine. it works on staging. it does not work in prod. prod is on fire. my machine is fine.`,
					Likes:   4501,
					Comments: []Comment{
						{Author: "@nullpointer", Body: "have you tried staging the prod", At: h(6 * time.Hour)},
					},
				},
				{
					SHA: "doc14te", Author: "@devops_bard", At: h(30 * time.Hour),
					Message: `the docs are outdated. the docs about the docs are outdated. the README links to a wiki that 404s. the truth lives in one Slack message from 2022.`,
					Likes:   3340,
				},
			},
		},
	}
}
